package com.ase.userservice.services;

import com.ase.userservice.entities.Exam;
import com.ase.userservice.entities.user.Lecturer;

import java.time.LocalDate;
import java.util.Calendar;
import java.util.Date;
import java.util.List;
import java.util.UUID;

public class DummyData {
  public static List<Exam> EXAMS = List.of(
      Exam.builder()
          .name("Mathematics Final Exam")
          .grade(1)
          .averageGrade(2)
          .totalPoints(100)
          .achievedPoints(95)
          .examType("Written")
          .date(LocalDate.of(2015,10,12))
          .time(5400)
          .allowedResources("Calculator, Formula Sheet")
          .attempt(1)
          .etcs(5)
          .room("Room A101")
          .lecturer(new Lecturer())
          .module("Mathe")
          .build(),
      Exam.builder()
          .name("Physics Midterm")
          .grade(2)
          .averageGrade(3)
          .totalPoints(80)
          .achievedPoints(65)
          .examType("Oral")
          .date(LocalDate.of(2015,10,12))
          .time(5400)
          .allowedResources("None")
          .attempt(1)
          .etcs(4)
          .room("Room B202")
          .lecturer(new Lecturer())
          .module("Physics")
          .build(),
      Exam.builder()
          .name("Computer Science Project")
          .grade(1)
          .averageGrade(2)
          .totalPoints(50)
          .achievedPoints(48)
          .examType("Project")
          .date(LocalDate.of(2015,10,12))
          .time(5400)
          .allowedResources("Laptop, IDE")
          .attempt(1)
          .etcs(6)
          .room("Online Submission")
          .lecturer(new Lecturer())
          .module("CS I")
          .build(),
      Exam.builder()
          .name("Chemistry Lab Exam")
          .grade(3)
          .averageGrade(2)
          .totalPoints(60)
          .achievedPoints(40)
          .examType("Practical")
          .date(LocalDate.of(2015,10,12))
          .time(5400)
          .allowedResources("Lab Equipment, Safety Manual")
          .attempt(2)
          .etcs(3)
          .room("Lab C303")
          .room("Online Submission")
          .lecturer(new Lecturer())
          .module("Chemistry")
          .build(),
      Exam.builder()
          .name("History Essay Exam")
          .grade(2)
          .averageGrade(2)
          .totalPoints(70)
          .achievedPoints(60)
          .examType("Essay")
          .date(LocalDate.of(2015,10,12))
          .time(5400)
          .allowedResources("Notes, Textbook")
          .attempt(1)
          .etcs(5)
          .room("Room D404")
          .lecturer(new Lecturer())
          .module("History I")
          .build(),
      Exam.builder()
          .name("History Essay Exam")
          .grade(2)
          .averageGrade(2)
          .totalPoints(70)
          .achievedPoints(60)
          .examType("Essay")
          .date(LocalDate.of(2015,10,12))
          .time(5400)
          .allowedResources("Notes, Textbook")
          .attempt(1)
          .etcs(5)
          .room("Room D404")
          .lecturer(new Lecturer())
          .module("History I")
          .build()
  );
}
